### ISSUE TITLE
Problems when running the program

### ISSUE THREAD

**Issue by wwwwwyyyyyxxxxx** [RU-Automated-Reasoning-Group/pi-PRL#1]
Hello! I'm trying to run the example in the README by running "python3 pi_PRL.py". However I got error like
```
not enough values to unpack (expected 5, got 4)
Timeout Error raised... Trying again
Traceback (most recent call last):
  File "pi_PRL.py", line 664, in <module>
    plot_keys=['stoc_pol_mean', 'running_score'])
  File "/home/wyx/Documents/Analogy/code/pi-PRL/mjrl/utils/train_agent.py", line 153, in train_agent_flip
    stats = agent.train_step(**args)
  File "/home/wyx/Documents/Analogy/code/pi-PRL/mjrl/algos/batch_reinforce.py", line 84, in train_step
    paths = trajectory_sampler.sample_paths(**input_dict)
  File "/home/wyx/Documents/Analogy/code/pi-PRL/mjrl/samplers/core.py", line 144, in sample_paths
    for result in results:
TypeError: 'NoneType' object is not iterable
```
Would you like to help me with that?

And I also noticed that if I run the code directly, I'll get error like
```
'numpy.random._generator.Generator' object has no attribute 'randn'
```
I tried to fix it by substitute all "self.np_random" by "np.random". Maybe this cause the first error. Would you like to share with me the numpy version you used in the project?

**Comment by Roadsong** [comment]
Hi, thanks for your questions.

My numpy version is ```1.19.2```

If you debug in a bottom-up manner, you may find the results is empty so that it is not iterable.
```
for result in results:
TypeError: 'NoneType' object is not iterable
```

https://github.com/RU-Automated-Reasoning-Group/pi-PRL/blob/53721e614922db848e5e4437bcb0f1e1b50ef9c8/mjrl/samplers/core.py#L138

Seems like a parallel issue so it wouldn't return properly? You may set the ```num_cpu``` in ```train_agent_flip``` function to a smaller number or even 1 to see if the issue can be resolved.

**Comment by wwwwwyyyyyxxxxx** [comment]
Thanks for your help! 

I found the error is caused by the gym version. gym change the api of wrappers/time_limit.py so I got "not enough values to unpack (expected 5, got 4)" error. It will be helpful to specify the gym version you used in the README. 

I'll close this issue.


> Hi, thanks for your questions.
> 
> My numpy version is `1.19.2`
> 
> If you debug in a bottom-up manner, you may find the results is empty so that it is not iterable.
> 
> ```
> for result in results:
> TypeError: 'NoneType' object is not iterable
> ```
> 
> https://github.com/RU-Automated-Reasoning-Group/pi-PRL/blob/53721e614922db848e5e4437bcb0f1e1b50ef9c8/mjrl/samplers/core.py#L138
> 
> Seems like a parallel issue so it wouldn't return properly? You may set the `num_cpu` in `train_agent_flip` function to a smaller number or even 1 to see if the issue can be resolved.

**Comment by Skywuuuu** [comment]
https://github.com/RU-Automated-Reasoning-Group/pi-PRL/issues/1#issuecomment-1491286080
@wwwwwyyyyyxxxxx 

Hi, I also encouter this error "not enough values to unpack (expected 5, got 4)". How to solve this error?

Thank you!!!

**Comment by Roadsong** [comment]
@Skywuuuu can you try this version of gym?
https://github.com/RU-Automated-Reasoning-Group/pi-PRL/blob/93b3197b3a7ae667edfcc5d767d9e51153a12e1a/requirements.txt#L9

**Comment by wwwwwyyyyyxxxxx** [comment]
Hi!

I found the error is caused by the gym version. gym change the api of wrappers/time_limit.py so I got "not enough values to unpack (expected 5, got 4)" error. You can downgrade gym to 0.21.0

> [#1 (comment)](https://github.com/RU-Automated-Reasoning-Group/pi-PRL/issues/1#issuecomment-1491286080) @wwwwwyyyyyxxxxx
> 
> Hi, I also encouter this error "not enough values to unpack (expected 5, got 4)". How to solve this error?
> 
> Thank you!!!

**Comment by Skywuuuu** [comment]
Thank you everyone!! I solve this problem by following this [stackoverflow](https://stackoverflow.com/questions/74060371/gym-super-mario-bros-7-3-0-valueerror-not-enough-values-to-unpack-expected). However, I think downgrading gym might work as well.
